package com.mycompany.tim;

// Imports we need for events, date, and dialog
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/*
 * Main class for the window
 * This class extends JFrame (a normal window)
 */
public class MyTimer extends javax.swing.JFrame {

    /*
     * Constructor
     * This runs when the window is created
     */
    public MyTimer() {
        initComponents(); // Build UI (label, layout, window)

        // Get today's date from the system
        LocalDate todayDate = LocalDate.now();

        // Check current month
        // Month number: January = 1
        if (todayDate.getMonthValue() != 1) {

            // If month is NOT January, show reject message
            JOptionPane.showMessageDialog(
                    this,
                    "Access denied! This program works only in January."
            );

            // Stop running the rest of the code
            return;
        }

        /*
         * Swing Timer
         * This runs code every 500 milliseconds (0.5 second)
         */
        javax.swing.Timer flashTimer = new javax.swing.Timer(500, new ActionListener() {

            // This variable controls show / hide
            boolean visible = true;

            /*
             * This method runs every 500ms
             */
            @Override
            public void actionPerformed(ActionEvent e) {

                // Show or hide the label
                jLabel1.setVisible(visible);

                // Flip the value (true -> false, false -> true)
                visible = !visible;
            }
        });

        // Start the blinking timer
        flashTimer.start();
    }

    /*
     * This method creates all UI components
     * It is auto-generated by NetBeans
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        // Create label
        jLabel1 = new javax.swing.JLabel();

        // Close app when window is closed
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // Text inside the label
        jLabel1.setText("Blinking Text");

        // Layout setup
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        // Resize window to fit components
        pack();
    }

    /*
     * Main method
     * Program starts from here
     */
    public static void main(String args[]) {

        // Run UI safely on Event Dispatch Thread
        java.awt.EventQueue.invokeLater(() -> {
            new MyTimer().setVisible(true);
        });
    }

    // UI variable (label)
    private javax.swing.JLabel jLabel1;
}
